version: "3.8"


services:  
# Listando services de acordo com a cadeira de prioridade de dependencia.
  chat-service:
    build:
      context: ./chat-service
    volumes:
      - ./chat-service:/chat-service/
      - /chat-service/node_modules
    ports:
      - 7100:7100

  api-gateway:
    build:
      context: ./api-gateway
    volumes:
      - ./api-gateway:/api-gateway/
      - /api-gateway/node_modules
    ports:
      - 7000:7000
    depends_on:
      - chat-service

  chat-front-app:
    build:
      context: ./chat-app
    env_file: ./chat-app/.env
    volumes:
      - ./chat-app:/chat-app/
      - /chat-app/node_modules
    ports:
      - 7001:7001
    depends_on:
      - api-gateway
  
