version: "3.8"


services:  
  api-gateway:
    build:
      context: ./api-gateway
    volumes:
      - ./api-gateway:/api-gateway/
      - /api-gateway/node_modules
    ports:
      - 7000:7000

  chat-front-app:
    build:
      context: ./chat-app
    env_file: ./chat-app/.env
    volumes:
      - ./chat-app:/chat-app/
      - /chat-app/node_modules
    ports:
      - 7001:7001
    depends_on:
      - api-gateway
  
